# Generated by Django 3.2.9 on 2022-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FibModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.PositiveBigIntegerField()),
                ('output', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(blank=True, choices=[('success', 'SUCCESS'), ('error', 'ERROR'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
